### ISSUE TITLE
Error "out of the box" when using USimpleGUI class

### ISSUE THREAD

**Issue by Protonumerique** [mariuswatz/modelbuilder#6]
I'm checking the examples but the ones using USimpleGUI instances throw this exception:

Exception in thread "Animation Thread" java.lang.NoSuchMethodError: controlP5.ControlP5.setMoveable(Z)V
    at unlekker.util.USimpleGUI.<init>(USimpleGUI.java:26)
    at RandomWalkLine3d.initGUI(RandomWalkLine3d.java:84)
    at RandomWalkLine3d.setup(RandomWalkLine3d.java:57)
    at processing.core.PApplet.handleDraw(PApplet.java:1608)
    at processing.core.PApplet.run(PApplet.java:1530)
    at java.lang.Thread.run(Thread.java:680)

But the method is actually found on controlP5,  an the sources of both libraries seem to match, but haven't been able to fix it. Just checking if it's me or for everyone.

The platform is macOSX 10.7.4, Processing 1.5.1, controlP5 0.7.5, modelBuilder v0007a03

**Comment by mariuswatz** [comment]
The problem is likely controlP5 0.7.5, I developed Modelbuilder using v.0.5.4. Apologies for not making that clear in the released code.

**Comment by mariuswatz** [comment]
For future reference, pre-Processing 2.0 versions of Modelbuilder uses ControlP5 0.5.4, versions for Processing 2.0 beta currently uses ControlP5 2.0.4.
